// <auto-generated />
using KetabInfo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ketab.Migrations
{
    [DbContext(typeof(DBAccess))]
    [Migration("20221222084627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("KetabInfo.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BooksInfo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Classic",
                            Name = "The Great Gatsby",
                            Writer = "Classic F.Scott Fitzgerald",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Classic",
                            Name = "Pride and Prejudice",
                            Writer = "Jane Austen",
                            Year = 1813
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Historical fiction",
                            Name = "Wolf Hall",
                            Writer = "Hilary Mantel",
                            Year = 2009
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Historical fiction",
                            Name = "All the Light We Cannot See",
                            Writer = "Anthony Doerr",
                            Year = 2014
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Humour and satire",
                            Name = "The Sellout",
                            Writer = "Paul Beatty",
                            Year = 2015
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Humour and satire",
                            Name = "Cat's Cradle",
                            Writer = "Kurt Vonnegut",
                            Year = 1963
                        },
                        new
                        {
                            Id = 7L,
                            Category = " Adventure stories",
                            Name = "Treasure Island",
                            Writer = "Robert Louis Stevenson",
                            Year = 1882
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Adventure stories",
                            Name = "The Call of the Wild",
                            Writer = "Jack London",
                            Year = 1903
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Crime",
                            Name = "The Silent Patient",
                            Writer = "Alex Michaelides",
                            Year = 2019
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Crime",
                            Name = "The Girl with the Dragon Tattoo",
                            Writer = "Stieg Larsson",
                            Year = 2005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
