// <auto-generated />
using Ketab;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ketab.Migrations
{
    [DbContext(typeof(DBAccess))]
    [Migration("20221222060431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Ketab.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BooksInfo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Clasic",
                            Name = "The Great Gatsby",
                            Writer = "F. Scott Fitzgerald",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Clasic",
                            Name = "Pride and Prejudice",
                            Writer = "Jane Austen",
                            Year = 1813
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
